InubashiriBlog/InubashiriBlogDemo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

from .views import index


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),  # 国际化配置
]

# 国际化路由
urlpatterns += i18n_patterns(
    path(_(""), index, name="index"),
    path(_('admin/'), admin.site.urls),
    path(_("blog/"), include("blog.urls", namespace='blog')),
    path(_("auth/"), include("blog_auth.urls", namespace="blog_auth")),
)

# 媒体文件处理 (确保在开发环境中能够正确访问媒体文件)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InubashiriBlog/blog/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @FileName    :urls.py
# @Time        :2024/9/3 下午5:04
# @Author      :InubashiriLix

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('index', views.all_blog, name='index'),
    path('detail/<int:blog_id>', views.detail_blog, name='blog_detail'),
    path('pub', views.pub_blog, name='pub_blog'),
    path('comment/pub', views.pub_comment, name='pub_comment'),
    path('search', views.search_blog, name='search_blog'),
]

InubashiriBlog/blog_auth/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @FileName    :urls.py
# @Time        :2024/9/4 下午6:01
# @Author      :InubashiriLix

from django.urls import path
from . import views

app_name = 'blog_auth'

urlpatterns = [
    path('login', views.blog_login, name='login'),
    path('register', views.register, name='register'),
    path('captcha', views.send_email_captcha, name='email'),
    path('logout', views.auth_logout, name='auth_logout'),
    path('profile', views.get_profile_page, name='profile'),
]

InubashiriBlog/templates/base.html
{#{% load static %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - InuLixBlog</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {% block head %}{% endblock %}

</head>
<body>
<header class="p-3 text-bg-dark mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url "index" %}"
               class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
                <img src="{% static "images/logo.jpg" %}" alt="">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url "index" %}" class="nav-link px-2 link-secondary text-light">Index</a></li>
                <li><a href="{% url "blog:index" %}" class="nav-link px-2 link-secondary text-light">All Blogs</a></li>
                <li><a href="{% url "blog:pub_blog" %}" class="nav-link px-2 link-secondary text-light">Pub Blog</a>
                </li>
            </ul>

            <form action="{% url 'blog:search_blog' %}" method="GET" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3"
                  role="search">
                <input type="search" name="q" class="form-control" placeholder="Search..." aria-label="Seach">
            </form>

            {% if not user.is_authenticated %}
                <div class="text-end">
                    <a href="{% url 'blog_auth:login' %}" type="button" class="btn btn-outline-primary me-2">Login</a>
                    <a href="{% url 'blog_auth:register' %}" type="button" class="btn btn-primary">Register</a>
                </div>
            {% else %}

                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {% if not avatar %}
                            <img src="{% static 'images/default_avatar.jpg' %}" alt="mdo" width="40" height="40"
                                 class="rounded-circle">
                        {% else %}
                            <img src="{{ avatar }}" alt="user avatar" width="40" height="40" class="rounded-circle">
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li><a class="dropdown-item" href="{% url "blog:pub_blog" %}">Pub Blog</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="{% url "blog_auth:profile" %}">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url "blog_auth:auth_logout" %}">Sign out</a></li>
                    </ul>
                </div>
            {% endif %}

        </div>
    </div>
</header>

{% block main %}
{% endblock %}


</body>
</html>

InubashiriBlog/templates/blogIndex.html
{% extends 'base.html' %}

{% block title %}ALL BLOG{% endblock %}

{% block main %}
    <main class='container p-4 rounded bg-white'>
        <h1>All Blogs</h1>
        <div class="row row-gap-4 row-cols-2">

            {% for item in blogs %}
                <div class="col">

                    <div class="card">
                        <div class="card-header">
                            <a href="{% url 'blog:blog_detail' blog_id=item.blog.id %}">{{ item.blog.title }}</a>
                        </div>
                        <div class="card-body" style="height: 100px">
                            <p class="card-text" style="height: 80px;">
                                {{ item.blog.description }}
                            </p>
                        </div>
                        <div class="card-footer text-body-secondary d-inline-flex justify-content-between">
                            <div>
                                {% if item.avatar %}
                                    <img src="{{ item.avatar }}" alt="user avatar" width="40" height="40"
                                         class="rounded-circle">
                                {% else %}
                                    <img src="{% static 'images/default_avatar.jpg' %}" class="rounded-circle"
                                         width="40" height="40">
                                {% endif %}
                                {# TODO: use author avatar#}
                                {{ item.blog.author.username }}
                            </div>
                            <div>
                                {{ item.blog.pub_time|date:"Y-m-d H:i:s" }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}


        </div>
    </main>
{% endblock %}

InubashiriBlog/templates/blog_detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/default.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}

{% block main %}
    <main class="container bg-white p-3 rounded">
        <h1> {{ blog.title }} </h1>
        <hr>

        <div class="mt-2">
            {% if not author_avatar %}
                <img src="{% static 'images/default_avatar.jpg' %}" alt="mdo" width="40" height="40"
                     class="rounded-circle">
            {% else %}
                <img src="{{ author_avatar }}" alt="user avatar" width="40" height="40" class="rounded-circle">
            {% endif %}
            {## TODO: CHECK#}
            <span class="ms-2">{{ blog.author.username }}</span>
            <span class="ms-2"> release at </span>
            <span class="ms-2"> {{ blog.pub_time|date:"Y,m,d " }}</span>
            <span class="ms-2"> y,m,d </span>
            <span class="ms-2"> {{ blog.pub_time|date:" H:i:s" }}</span>
        </div>
        <hr>

        <div class="py-2">
            {{ blog.content|safe }}
        </div>

        <hr>

        <div class="mt-2">
            <h3>Comment ({{ blog.comments.all|length }})</h3>

            <form action="{% url 'blog:pub_comment' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="blog_id" value="{{ blog.id }}">
                <div class="mt-2">
                    <input type="text" class="container" placeholder="enter comments please" name="content">
                </div>
                <div class="text-end mt-2">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>

        <hr>

            <div class="mt-2">
                <ul class="list-group list-group-flush">

                    {% for item in comments %}
                        <li class="list-group-item">
                            <div class="d-flex justify-content-between text-body-secondary">
                                <div class="user-info">
                                    {% if not item.comment_avatar %}
                                        <img src="{% static 'images/default_avatar.jpg' %}" alt="mdo" width="32" height="32"
                                             class="rounded-circle">
                                    {% else %}
                                        <img src="{{ item.comment_avatar }}" class="rounded-circle" width="40"
                                             height="40" alt="">
                                    {% endif %}

                                    <span class="ms-2">{{ item.comment.author.username }}</span>
                                </div>

                                <div class="create-time" style="line-height: 40px">
                                    {{ item.comment.pub_time|date:"Y-m-d H:i:s" }}
                                </div>
                            </div>
                            <div class="mt-2">{{ item.comment.content }}</div>
                        </li>

                    {% endfor %}
                </ul>

            </div>
        </div>
        <hr>
    </main>

    <script>
        hljs.highlightAll();
    </script>

{% endblock %}

InubashiriBlog/templates/error_invalid_blog.html
{% extends 'base.html' %}

{% block title %}ERROR!{% endblock %}

{% block main %}
<main class="container bg-white p-3 rounded">
    <h1> BLOG NOT FOUND!</h1>
    <div class="alert alert-warning" role="alert">
      PAGE NOT FOUND!
      Error Reason: {{ error }}
    </div>
</main>
{% endblock %}

InubashiriBlog/templates/index.html
{% extends 'base.html' %}

{% block title %}WELCOME!{% endblock %}

{% block header %} {% endblock %}

{% block main %}
    <main class='container p-4 rounded bg-white'>
        <h2>INTRO / 介绍</h2>
        <p>This is a website created by a student in XJTLU, aiming at gathering SAT files.</p>
        <p>这是一个西交利物浦学生创作的网站，主要用于整理SAT专业的资料。</p>
        <p><br></p>
        <p>Due to I'm in ICS (infomation and computing science), I'll mainly update files about ICS.</p>
        <p>因为我是ics专业的，所以我上传的资料将会主要集中于本专业。</p>
        <p>Of cources, I'm also interested in other classes, so I'll also upload the other classes</p>
        <p>当然，我也对其他专业有兴趣，所以也会更新别的专业的课程。</p>
        <p><br></p>
        <p>main resouces:</p>
        <p>大概的信息来源：</p>
        <p>books（always without copy right）</p>
        <p>CSDIY</p>
        <p>ZHIHU</p>
        <p>CSDN </p>
        <p>GitHub</p>
        <p>课件</p>
        <p>投稿</p>
        <p>Why? / 为啥创建了这个网站？</p>
        <p>
            回顾大一，花两个月学了个python，浑浑噩噩过了个暑假，然后又去学了一点单片机（可能这辈子就和arduino过了），搭积木一样搞了几个小玩意，其他拿的出手的也没啥了，大一完结。</p>
        <p>大二，2024.9，就是差不多现在，接触到了一个神人 <a href="https://space.bilibili.com/31341757" target="_blank">https://space.bilibili.com/31341757</a>
            还有一个自学网站（csdiy），被震撼到了，同时学习兴趣被极大的点燃了，啥都想学一点，又想着也不能太宽泛而没深度，加上最近在哈欠中学了一周学的Django，于是有所启发，想着搞一个博客用来汇总资源会好一点。
        </p>
        <p>大概就这些想法了。</p>
        <h2>DDL：</h2>
        <p>大概打算在12月前把这个网站全搞完，网站更新计划会后继发布。</p>
        <p><br></p>
    </main>

{% endblock %}

InubashiriBlog/templates/login.html
{% extends 'base.html' %}

{% block title %}LOGIN{% endblock %}

{% block main %}
    <main class='container p-4 rounded bg-white'>
        <div style="max-width: 330px;" class="m-auto">
            {% if not user.is_authenticated %}
                <h1>LOGIN</h1>
            {% else %}
                <h1>LOGIN OTHER ACCOUNT</h1>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                <div class="mb-3">
                    <label>Email</label>
                    <input type="email" name="email" class="form-control" placeholder="enter your Email">
                    {% if form.email.errors %}
                        <ul>
                            {% for error in form.email.errors %}
                                <ul>
                                    <li>{{ error }}</li>
                                </ul>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control" placeholder="enter password">
                    {% if form.password.errors %}
                        <ul>
                            {% for error in form.password.errors %}
                                <ul>
                                    <li>{{ error }}</li>
                                </ul>
                            {% endfor %}
                        </ul>
                    {% endif %}

                </div>

                <div class="checkbox mb-3">
                    <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        Remember me
                    </label>
                </div>
                <div class="mb-3">
                    <button class="btn-primary w-100">Login!</button>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

InubashiriBlog/templates/profile.html
{% extends 'base.html' %}

{% block title %}PROFILE{% endblock %}

{% block main %}

    {#    AVATAR DONE#}
    {#    TODO: beatify#}
    <main class='container p-4 rounded bg-white'>
        <div>
            {% if not avatar %}
                <img src="{% static 'images/default_avatar.jpg' %}" alt="mdo" width="40" height="40"
                     class="rounded-circle">
            {% else %}
                <img src="{{ avatar }}" alt="user avatar" width="80" height="80" class="rounded-circle">
            {% endif %}
        </div>

        {% if form.errors %}
            <div class="alert alert-warning" role="alert">
                Error Reason:
                <ul>
                    {% for field, errors in form.errors.items %}
                        <li>{{ field }}: {{ errors }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <form action="{% url 'blog_auth:profile' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="avatar_file" class="form-label">Upload Avatar</label>
                <input type="file" name="avatar_file" id="avatar_file" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary" name="btn-submit">SUBMIT AVATAR</button>
        </form>
    </main>

    {#   blog section#}
    {#    Done: views#}
    {#    TODO: beati#}

    <div>
        <ul>
            {% if blogs %}
                <h3>Blogs </h3>
                {% for blog in blogs %}
                    <li>
                        <div class="card">
                            <div class="card-header">
                                <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                            </div>
                            <div class="card-body" style="height: 40px">
                                <p class="card-text" style="height: 30px;">
                                    {{ blog.description|truncatechars:30 }}
                                </p>
                            </div>
                            <div class="card-footer text-body-secondary d-inline-flex justify-content-between">
                                <div>
                                    {{ blog.author.username }}
                                </div>
                                <div>
                                    {{ blog.pub_time|date:"Y-m-d H:i:s" }}
                                </div>
                            </div>
                        </div>
                        <hr>
                    </li>
                {% endfor %}
            {% else %}
                <h3>No Blog Here!</h3>
            {% endif %}
        </ul>
    </div>



{% endblock %}

InubashiriBlog/templates/pub_blog.html
{% extends 'base.html' %}

{% block title %}PUB BLOG{% endblock %}

{% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <style>
        #editor-wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}

{% block main %}

    {% if error_message %}
        <div id="error-container" class="alert alert-danger">
            {{ error_message }}
        </div>
    {% endif %}

    <main class='container p-4 rounded bg-white'>
        <h1>Pub Blog</h1>
        <div class="mt-3">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">Title</label>
                    <input type="text" name="title" placeholder="enter your title" class="form-control">
                </div>

                <div class="mb-3">
                    <label class="">Description</label>
                    <input type="text" name="description" id="description"
                           placeholder="enter your description, and it will be displayed with title on the main page"
                           class="form-control">
                </div>

                <div class="mb-3">
                    <label class="form-label">Category</label>
                    <select name="category" class="form-select" id="category-select">
                        {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="mb-3">
                    <label class="form-label">Content</label>
                    <div id="editor-wrapper">
                        <div id="toolbar-container"><!-- 工具栏 --></div>
                        <div id="editor-container"><!-- 编辑器 --></div>
                    </div>
                    <!-- 隐藏的 textarea 用于提交内容 -->
                    <textarea name="content" id="content-textarea" style="display:none;"></textarea>
                </div>

                <div class="mb-3 text-end">
                    <button class="btn btn-primary" id="submit-btn">Publish</button>
                </div>

            </form>
        </div>
    </main>
{% endblock %}

InubashiriBlog/templates/register.html
{% extends 'base.html' %}
{% block title %}REGISTER{% endblock %}
{% block head %}
    <script src="{% static "jquery/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "js/register.js" %}"></script>
{% endblock %}
{% block main %}
    <main class='container p-4 rounded bg-white'>
        <div style="max-width: 330px;" class="m-auto">
            <h1>REGISTER</h1>
            <form action="" method="POST">
                {% csrf_token %}

                {% if form.non_field_errors %}


                    <div class="alert alert-danger">
                        <ul>
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>


                {% endif %}

                <div class="mb-3">
                    <lable>Username</lable>
                    <input type="text" name="username" class="form-control" placeholder="enter your nickname">
                    {% if form.username.errors %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for error in form.username.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}

                </div>

                <div class="mb-3">
                    <label>Email</label>
                    <input type="email" name="email" class="form-control" placeholder="enter your Email" aria-describedby="emailHelpInline">
                    <div class="col-auto">
                        <span id="emailHelpInline" class="form-text">
                        Must be a Real Email that you can use.
                        {% if form.username.errors %}
                            <div class="alert alert-danger">
                                <ul>
                                    {% for error in form.username.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                        </span>
                    </div>
                </div>


                <div class="mb-3">
                    <label>Verification Code</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="captcha" placeholder="Enter Verification Code"
                               aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-secondary" type="button" id="captcha-btn">send code in email
                        </button>
                    </div>
                    {% if form.captcha.errors %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for error in form.captcha.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control" placeholder="enter password" aria-describedby="passwordHelpInline">
                    <div class="col-auto">
                        <span id="passwordHelpInline" class="form-text">
                          Must be 8-20 characters long.
                            {% if form.password.errors %}
                                <div class="alert alert-danger">
                            <ul>
                                {% for error in form.password.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                            {% endif %}
                        </span>
                    </div>


                </div>


                <div class="mb-3">
                    <button type="submit" class="btn-primary w-100">Register!</button>
                </div>
            </form>
        </div>

    </main>
{% endblock %}

InubashiriBlog/templates/search.html
{% extends 'base.html' %}

{% block title %}SEARCH RESULTS{% endblock %}

{% block main %}
    <main class='container p-4 rounded bg-white'>
        <h2>Search Result ({{ blogs.all|length }})</h2>
        <div class="row row-gap-4 row-cols-2">
            {% for item in blogs %}
                <div class="col">

                    <div class="card">
                        <div class="card-header">
                            <a href="{% url 'blog:blog_detail' blog_id=item.blog.id %}">{{ item.blog.title }}</a>
                        </div>
                        <div class="card-body" style="height: 100px">
                            <p class="card-text" style="height: 80px;">
                                {{ item.blog.description }}
                            </p>
                        </div>
                        <div class="card-footer text-body-secondary d-inline-flex justify-content-between">
                            <div>
                                {% if item.avatar %}
                                    <img src="{{ item.avatar }}" alt="user avatar" width="40" height="40"
                                         class="rounded-circle">
                                {% else %}
                                    <img src="{% static 'images/default_avatar.jpg' %}" class="rounded-circle"
                                         width="40" height="40">
                                {% endif %}
                                {# TODO: use author avatar#}
                                {{ item.blog.author.username }}
                            </div>
                            <div>
                                {{ item.blog.pub_time|date:"Y-m-d H:i:s" }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {#    TODO: navi bar  #}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
        </nav>
    </main>

{% endblock %}


{#TODO: add an personal page#}
{#TODO: multipages in sql#}